#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Add common.sh for Windows compatibility
. "$(dirname -- "$0")/common.sh"

# Run Biome check with write instead of apply
npx @biomejs/biome check --write .
